apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/sohansm-project/kfk/app:latest
        imagePullPolicy: "Always"
        env:
        - name: APP_ENV
          value: production
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "10.10.0.2:9094"
        - name: KAFKA_TOPIC
          value: gke-test-topic-2
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080